<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="container">
    <h1 class="mt-5">Список сайтов</h1>
    <table class="table" data-test="urls">
        <thead><tr><th>ID</th><th>Имя</th><th>Дата добавления</th></tr></thead>
        <tbody>
            <?php foreach ($urls as $url): ?>
            <tr>
                <td><?= $url['id'] ?></td>
                <td><a href="/urls/<?= $url['id'] ?>"><?= $url['name'] ?></a></td>
                <td><?= $url['created_at'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>