<?php
ob_start();
?>
<?php if (!empty($flash)): ?>
<div class="alert alert-<?= htmlspecialchars($flash['type']) ?>">
    <?= htmlspecialchars($flash['message']) ?>
</div>
<?php endif; ?>

<h1 class="display-4 mb-3">Сайт: <?= htmlspecialchars($url['name']) ?></h1>

<form method="post" action="/urls/<?= $url['id'] ?>/checks">
    <button type="submit" class="btn btn-primary mb-3">Запустить проверку</button>
</form>

<table class="table table-bordered w-50">
    <tr>
        <th>ID</th>
        <td><?= $url['id'] ?></td>
    </tr>
    <tr>
        <th>Имя</th>
        <td><?= htmlspecialchars($url['name']) ?></td>
    </tr>
    <tr>
        <th>Дата создания</th>
        <td><?= $url['created_at'] ?></td>
    </tr>
</table>

<h2 class="mt-4">Проверки</h2>

<table data-test="checks" class="table table-bordered table-hover mt-3">
    <thead>
        <tr>
            <th>ID</th>
            <th>Код ответа</th>
            <th>H1</th>
            <th>Title</th>
            <th>Description</th>
            <th>Дата создания</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($checks as $check): ?>
        <tr>
            <td><?= $check['id'] ?></td>
            <td><?= $check['status_code'] ?></td>
            <td><?= htmlspecialchars($check['h1'] ?? '') ?></td>
            <td><?= htmlspecialchars($check['title'] ?? '') ?></td>
            <td><?= htmlspecialchars($check['description'] ?? '') ?></td>
            <td><?= $check['created_at'] ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php
$content = ob_get_clean();
include __DIR__ . '/../layout.phtml';
?>